const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {createWorkflow}=require('./workflowCore');
const {validateRuntime}=require('./runtime');
const config=require('./config');
const workflow=createWorkflow(config);
const headers={'x-tenant-id':'tenant-a','idempotency-key':'request-a'};
function projectRoot(){let current=__dirname;while(current!==path.dirname(current)&&!fs.existsSync(path.join(current,'start.sh')))current=path.dirname(current);return current;}

test('domain workflow topology and typed connectors are declared',()=>{assert.ok(config.states.includes(config.initialState));assert.ok(config.transitions.length>5);assert.ok(config.connectors.length>5);for(const transition of config.transitions){assert.ok(config.states.includes(transition.from));assert.ok(config.states.includes(transition.to));assert.ok(transition.roles.length);}});
test('tenant idempotency actor and create roles fail closed',()=>{assert.throws(()=>workflow.context({}, {id:'a',role:config.createRoles[0]}),/X-Tenant-Id/);const ctx=workflow.context(headers,{id:'creator-a',role:config.createRoles[0]});const record=workflow.createCase({subjectRef:'subject-17',policyVersion:'p1',effectiveAt:'2026-07-18T00:00:00Z',sourceSnapshot:{version:'v1'}},ctx);assert.equal(record.state,config.initialState);assert.equal(record.tenantId,'tenant-a');assert.throws(()=>workflow.createCase({subjectRef:'subject-17',policyVersion:'p1',effectiveAt:'2026-07-18T00:00:00Z'},{...ctx,role:'visitor'}),/Role cannot create/);});
test('evidence is opaque typed and digest verified',()=>{assert.equal(workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'vault:evidence-17',sourceVersion:'v1',sha256:'a'.repeat(64),capturedAt:'2026-07-18T10:00:00Z'}).sha256,'a'.repeat(64));assert.throws(()=>workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'vault:x',sourceVersion:'v1',sha256:'bad',capturedAt:'2026-07-18T10:00:00Z'}),/sha256/);assert.throws(()=>workflow.evidence({kind:config.evidenceKinds[0],sourceRef:'vault:x',sourceVersion:'v1',sha256:'b'.repeat(64),capturedAt:'2026-07-18T10:00:00Z',metadata:{raw_content:'secret'}}),/opaque references/);});
test('outbox directives are typed opaque and bounded for retry',()=>{const item=workflow.outbox({provider:config.connectors[0].name,operation:'sync_receipt',payload:{version:'v1'},maxAttempts:3});assert.equal(item.provider,config.connectors[0].name);assert.equal(item.maxAttempts,3);assert.throws(()=>workflow.outbox({provider:'undeclared',operation:'sync',payload:{version:'v1'}}),/declared connector/);assert.throws(()=>workflow.outbox({provider:config.connectors[0].name,operation:'sync',payload:{raw_content:'secret'}}),/opaque references/);assert.throws(()=>workflow.outbox({provider:config.connectors[0].name,operation:'sync',maxAttempts:20}),/maxAttempts/);});
test('versioned acceptance fixture is deterministic and never executes the consequential action',()=>{const ctx=workflow.context(headers,{id:'reviewer-a',role:config.assessmentRoles[0]});assert.equal(workflow.deterministicAssessment({},ctx).disposition,'insufficient_evidence');const accepted=workflow.deterministicAssessment(config.acceptedFixture,ctx);assert.equal(accepted.disposition,config.readyDisposition);assert.equal(accepted[config.decisionField],null);assert.equal(accepted.automatedDecision,false);assert.equal(accepted.requiresHumanReview,true);assert.equal(workflow.deterministicAssessment(config.rejectedFixture,ctx).disposition,config.holdDisposition);});
test('transitions enforce evidence optimistic versions RBAC and dual control',()=>{const first=config.transitions[0];const ctx=workflow.context(headers,{id:'actor-b',role:first.roles[0]});const record={state:first.from,version:1,evidenceCount:0,createdBy:'actor-a',lastActorId:null};assert.throws(()=>workflow.transition(record,{action:first.action,expectedVersion:1,reason:'reviewed authoritative evidence'},ctx),/evidence/);assert.throws(()=>workflow.transition({...record,evidenceCount:1},{action:first.action,expectedVersion:2,reason:'reviewed authoritative evidence'},ctx),/changed/);assert.equal(workflow.transition({...record,evidenceCount:1},{action:first.action,expectedVersion:1,reason:'reviewed authoritative evidence'},ctx).to,first.to);const dual=config.transitions.find(item=>item.dualControl);const dualCtx=workflow.context(headers,{id:'actor-b',role:dual.roles[0]});assert.throws(()=>workflow.transition({state:dual.from,version:2,evidenceCount:1,createdBy:'actor-a',lastActorId:'actor-b'},{action:dual.action,expectedVersion:2,reason:'independent approval complete'},dualCtx),/second person/);});
test('runtime rejects weak secrets wildcard CORS and production legacy flags',()=>{assert.throws(()=>validateRuntime({NODE_ENV:'test',JWT_SECRET:'short'}),/JWT_SECRET/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'*'}),/allowlist/);assert.throws(()=>validateRuntime({NODE_ENV:'production',JWT_SECRET:'x'.repeat(40),DATABASE_URL:'postgres://configured',CORS_ORIGINS:'https://client.example',ENABLE_LEGACY_PROVIDER_ROUTES:'true'}),/prohibited/);assert.equal(validateRuntime({NODE_ENV:'test',JWT_SECRET:'x'.repeat(40)}),true);});
test('additive migration and launcher preserve audit outbox and nondestructive boundaries',()=>{const project=projectRoot();const migration=fs.readFileSync(path.join(__dirname,'../migrations/001_governed_tenant_matter.sql'),'utf8');const launcher=fs.readFileSync(path.join(project,'start.sh'),'utf8');assert.equal((migration.match(/^BEGIN;/gm)||[]).length,1);assert.equal((migration.match(/^COMMIT;/gm)||[]).length,1);assert.equal((migration.match(/RETURNS trigger LANGUAGE plpgsql AS \$\$/g)||[]).length,(migration.match(/^\$\$;/gm)||[]).length);assert.match(migration,/receipt_sha256 CHAR\(64\) CHECK/);assert.match(migration,/governed_connector_failures[\s\S]*case_id UUID NOT NULL/);assert.match(migration,/governed_tenant_memberships/);assert.match(migration,/governed_outbox/);assert.match(migration,/governed_outbox_attempts/);assert.match(migration,/dead_letter/);assert.match(migration,/append-only/);assert.match(migration,new RegExp(config.caseType));assert.doesNotMatch(migration,/DROP TABLE|TRUNCATE/);assert.doesNotMatch(launcher,/kill\s+-9|pkill|dropdb|createdb|npm\s+install|seed\.js|psql\s+.*-f/);});



