"""Explicit semantic feature map plus traceable source-route/panel coverage."""
from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parent.parent
features=[]
def add(group,id,title,fields='',ai=False,mode='records',description=''):
 features.append(dict(id=id,title=title,group=group,description=description or f'Manage {title.lower()} in your shared legal workspace.',ai=ai,mode=mode,fields=[dict(name=n,label=n.replace('_',' ').capitalize(),type=('date' if n.endswith('_date') else 'number' if any(w in n for w in ['amount','hours','rate','cost','value','income','percentage','years']) else 'textarea' if any(w in n for w in ['content','details','text','instructions','facts','terms','position']) else 'text')) for n in fields.split()],sources=[]))
def batch(group,rows):
 for row in rows:add(group,*row)
batch('Practice',[
('clients','Clients','full_name email phone company address'),('matters','Matters & cases','case_number jurisdiction opposing_party opened_date'),('contacts','Contacts','full_name email phone organization relationship'),('leads','Leads & intake','full_name email phone referral_source intake_details',True),('tasks','Tasks','assignee due_date priority'),('calendar','Calendar & court dates','event_date location attendees',True),('deadlines','Deadlines & reminders','due_date deadline_type jurisdiction',True),('notes','Case notes','content'),('filings','Court filing records','filing_type court filing_date reference'),('filing-service','Service of process','recipient service_date service_method proof'),('conflicts','Conflict checks','parties relationships conflict_details',True),('reports','Reports & analytics','',False,'report')])
batch('Documents & research',[
('documents','Documents','document_type content',True),('drafting','Document drafting','document_type jurisdiction parties instructions',True),('templates','Document templates','document_type content',True),('contract-review','Contract review','contract_text review_focus',True),('summaries','Document summaries','document_text summary_focus',True),('research','Legal research & citations','question jurisdiction source_text',True),('depositions','Deposition summaries','transcript_text questions',True),('discovery','Discovery & evidence review','evidence_text review_instructions',True),('ocr','OCR & document extraction','document_type extracted_text',False,'integration'),('transcription','Voice notes & transcription','transcript_text language',False,'integration'),('translation','Translation & language detection','source_language target_language source_text',True),('case-analysis','Case assessment & strategy','facts jurisdiction questions',True),('opponent-analysis','Opponent research','opponent_name known_facts source_text',True),('patents','Patent analysis','invention_details claims_text source_text',True),('trademarks','Trademark research','mark_name goods_services source_text',True),('compliance','Multi-jurisdiction compliance','jurisdiction requirements source_text',True),('glossary','Legal glossary','term definition context',True)])
batch('Finance',[
('time','Time tracking','work_date hours rate description',True),('billing','Invoices & billing','invoice_number amount due_date payment_status',True),('expenses','Expenses','expense_date amount category receipt_reference'),('billing-rates','Billing rates','role rate currency'),('trust','Trust accounts & ledgers','account_name transaction_type amount transaction_date reference'),('trust-reconciliation','Trust & retainer reconciliation','statement_date bank_balance ledger_balance outstanding_amount',False),('payments','Payment processing','amount currency reference',False,'integration'),('fee-estimator','Court fees & cost estimates','court jurisdiction amount estimate_details',True),('subscription','Subscription & payment methods','plan_name renewal_date',False,'integration')])
batch('Family law',[
('family-documents','Family law documents','document_type party1_name party2_name jurisdiction key_terms',True),('custody','Child custody planning','child_name child_age current_arrangement desired_arrangement special_needs',True),('custody-assessment','Custody scenario assessment','facts jurisdiction parenting_history',True),('child-support','Child support planning','custodial_income non_custodial_income num_children healthcare_costs childcare_costs jurisdiction',True),('alimony','Alimony planning','requesting_income paying_income marriage_duration jurisdiction',True),('asset-division','Asset division','asset_name estimated_value ownership acquisition_date',True),('property','Property & valuations','property_name property_type address estimated_value mortgage_balance',True),('financial-disclosure','Financial disclosure','annual_income monthly_expenses total_assets total_debts employment_type',True),('parenting','Parenting plans & coordination','children_details schedule_type holiday_plan communication_method',True),('parenting-incidents','Parenting exchange incidents','incident_date location incident_details witnesses'),('mediation','Mediation','topic party1_position party2_position desired_outcome',True),('family-settlement','Family settlement agreements','party1_name party2_name asset_division support_terms custody_terms',True),('family-filing','Family court filing guidance','filing_type jurisdiction filing_date facts',True),('family-rights','Family law & state guidance','jurisdiction situation question source_text',True),('family-timeline','Divorce timeline','filing_date current_phase jurisdiction',True),('family-advisor','Family case advisor','question context',True)])
batch('Estate planning',[
('wills','Wills','testator_name executor_name witness_1 witness_2 content',True),('trust-planning','Trust planning','trust_name trust_type grantor trustee beneficiaries content',True),('power-of-attorney','Power of attorney','principal_name agent_name scope effective_date content',True),('healthcare-directives','Healthcare directives','patient_name healthcare_agent treatment_preferences content',True),('beneficiaries','Beneficiaries & suitability','full_name relationship email share_percentage',True),('digital-assets','Digital assets & accounts','asset_name asset_type platform value_estimate beneficiary'),('legacy-messages','Legacy messages & delivery plans','recipient message_content scheduled_date',True),('insurance','Insurance policies','policy_number insurer coverage_amount premium_amount renewal_date'),('estate-timeline','Estate timeline','event_date milestone responsible_person'),('executor','Executor tasks & access packets','executor_name task_details due_date document_references'),('estate-advisor','Estate planning advisor','family_details assets_details goals jurisdiction',True),('estate-tax','Estate tax planning','jurisdiction assets_details family_details source_text',True),('long-term-care','Long-term care planning','monthly_cost years inflation_percentage',True),('account-consolidation','Account consolidation','accounts_details goals',True),('family-meetings','Family meetings','meeting_date attendees agenda action_items',True),('beneficiary-portal','Beneficiary portal','beneficiary_name access_scope',False,'integration'),('international-estates','International estate planning','countries residency assets_details goals',True),('bank-aggregation','Bank & brokerage aggregation','institution account_reference',False,'integration')])
batch('Immigration',[
('visas','Visa categories & pathways','current_status nationality qualifications goals',True),('immigration-forms','Immigration form assistance','form_type applicant_details questions',True),('immigration-compliance','Immigration compliance','visa_type expiration_date requirements source_text',True),('uscis-tracking','USCIS receipt & status tracking','receipt_number form_type filed_date current_status'),('uscis-connection','USCIS provider connection','receipt_number',False,'integration'),('immigration-interview','Immigration interview preparation','visa_type applicant_details questions',True),('rfe','Requests for evidence','receipt_number notice_text response_due_date evidence_details',True),('immigration-plan','Immigration case planning','case_type facts goals milestones',True),('immigration-timeline','Immigration processing scenarios','form_type filed_date service_center source_text',True),('immigration-analytics','Immigration case comparisons','case_details comparison_data',True)])
batch('Small claims',[
('claims-jurisdiction','Small claims jurisdiction','state county claim_amount dispute_type',True),('demand-letters','Demand letters','opposing_party claim_amount facts deadline_date',True),('complaints','Small claims complaints','court opposing_party claim_amount facts',True),('hearing-prep','Hearing preparation & coaching','hearing_date facts questions',True),('evidence','Evidence organization','exhibit_label evidence_type evidence_details relevance',True),('settlement','Settlement evaluation','claim_amount costs_amount settlement_offer facts',True),('court-procedure','Court procedure checklists','court jurisdiction hearing_date checklist',True),('witness-statements','Witness statements','witness_name statement_text event_date',True),('appeals','Appeal assessment','judgment_date court decision_text grounds',True),('collection','Judgment collection','judgment_date debtor_name judgment_amount collected_amount',True),('limitations','Limitation period review','jurisdiction claim_type event_date source_text',True)])
batch('Team & communications',[
('messages','Messages & correspondence','recipient subject content',True),('notifications','Notification plans','recipient channel subject content scheduled_date'),('client-portal','Client portal','client_name access_scope',False,'integration'),('portal-assistant','Client portal assistant','question approved_case_summary',True),('team','Team & access directory','full_name email role'),('surveys','Client feedback surveys','client_name rating feedback'),('cle','Continuing education','course_name provider hours completion_date jurisdiction'),('malpractice','Malpractice insurance','insurer policy_number coverage_amount renewal_date'),('audit','Activity & audit log','',False,'audit')])
batch('Connections & settings',[
('esign','E-signatures','provider document_reference signers',False,'integration'),('efiling','Electronic court filing','provider court document_reference',False,'integration'),('court-records','Court records & PACER','court case_number',False,'integration'),('email','Email delivery & archive','provider mailbox',False,'integration'),('calendar-sync','Calendar synchronization','provider calendar_reference',False,'integration'),('webhooks','Webhooks & advisor connections','event_type endpoint_url',False,'integration'),('intake-forms','Intake form builder','form_name fields_details conditions',True),('saved-views','Saved views & dashboards','feature_id filters layout'),('website','Firm website generator','firm_name services audience instructions',True),('connections','Connection settings','provider service_name',False,'integration'),('security','Security & access settings','setting_name setting_details',False,'integration')])
extension=json.loads((ROOT/'config/legal-extension.json').read_text())
for definition in extension['features']:add(**definition)
byid={x['id']:x for x in features}
# Exact same name in two products can still have a different domain meaning.
special={
 'family-law':{'documents':'summaries','assets':'asset-division','custody':'custody','alimony':'alimony','document-gen':'family-documents','mediation':'mediation','filing':'family-filing','financial':'financial-disclosure','parenting':'parenting','property':'property','rights':'family-rights','settlement':'family-settlement','child-support':'child-support','timeline':'family-timeline','state-law':'family-rights','conversations':'family-advisor','predictive-ai':'custody-assessment'},
 'estate-planning':{'wills':'wills','trusts':'trust-planning','beneficiaries':'beneficiaries','digital-assets':'digital-assets','digital-accounts':'digital-assets','power-of-attorney':'power-of-attorney','healthcare-directives':'healthcare-directives','insurance-policies':'insurance','properties':'property','legacy-messages':'legacy-messages','estate-timeline':'estate-timeline','executor-tasks':'executor','executor-access-packet':'executor','ai-advisor':'estate-advisor','vault':'documents','legal':'compliance','ltc':'long-term-care','consol':'account-consolidation','family':'family-meetings','portal':'beneficiary-portal','intl':'international-estates'},
 'immigration':{'forms':'immigration-forms','compliance':'immigration-compliance','status-tracking':'uscis-tracking','case-assessment':'case-analysis','document-analysis':'summaries','form-assist':'immigration-forms','translate':'translation','compliance-check':'immigration-compliance','status-prediction':'immigration-timeline','deadline-predict':'immigration-timeline','agentic-case-manager':'immigration-plan','pathway-optimizer':'visas'},
 'legal-documents':{'drafting':'drafting','billing':'billing','conflicts':'conflicts','predictions':'case-analysis','calendar':'calendar','communications':'messages','intake':'leads','ediscovery':'discovery','pacer':'court-records','intake-builder':'intake-forms','matter-outcome':'case-analysis','transcription':'transcription'}
}
# Ordered semantic aliases collapse generated CF/gap routes and older product labels.
rules=[
(r'executor|access-packet','executor'),(r'beneficiar.*portal|beneficiary-experience','beneficiary-portal'),(r'beneficiar','beneficiaries'),(r'life-expectancy|long-term-care','long-term-care'),(r'family-meeting','family-meetings'),(r'international-planning','international-estates'),(r'account-consol','account-consolidation'),(r'tax-minim','estate-tax'),(r'agentic-estate','estate-advisor'),(r'digital-legacy|digital-account','digital-assets'),(r'video-message|legacy','legacy-messages'),(r'brokerage|bank-account-aggregation','bank-aggregation'),
(r'trust.*reconcil|retainer.*reconcil','trust-reconciliation'),(r'trust','trust'),(r'child-support|calculate-child','child-support'),(r'alimony','alimony'),(r'custody-outcome','custody-assessment'),(r'parenting.*incident','parenting-incidents'),(r'co-parent|coparent|family-communication','parenting'),(r'financial-asset-valuation','property'),(r'state-aware-legal','family-rights'),
(r'rfe','rfe'),(r'receipt|status-tracking','uscis-tracking'),(r'uscis-integration','uscis-connection'),(r'visa|pathway','visas'),(r'interview-prep','immigration-interview'),(r'agentic-case','immigration-plan'),(r'peer-case','immigration-analytics'),(r'immigration-form','immigration-forms'),
(r'jurisdiction.*playbook|^jurisdiction$','claims-jurisdiction'),(r'evidence','evidence'),(r'demand-letter','demand-letters'),(r'complaint','complaints'),(r'hearing-prep|pro-se-litigant','hearing-prep'),(r'settlement-calculator|settlementcalculator|case-evaluation-settlement','settlement'),(r'court-procedure|courtprocedure','court-procedure'),(r'witness','witness-statements'),(r'appeal','appeals'),(r'collection','collection'),(r'statute-of-limitations','limitations'),(r'fee-schedule|fee-prediction','fee-estimator'),
(r'efiling|e-filing','efiling'),(r'pacer|court-records|court-filing-integration','court-records'),(r'esign|e-sign|docusign','esign'),(r'webhook','webhooks'),(r'payment|court-fees','payments'),(r'subscription','subscription'),(r'calendar-sync','calendar-sync'),(r'imap|smtp','email'),(r'client-portal','client-portal'),(r'portal.*chat','portal-assistant'),(r'multi-tenant|audit-log-rbac|2fa|security|rbac','security'),(r'audit.*history|audit-log|activity','audit'),
(r'vision.*doc|document-ocr|ocr','ocr'),(r'transcri|voice-notes','transcription'),(r'discovery|ediscovery','discovery'),(r'deposition','depositions'),(r'contract.*draft','drafting'),(r'contract','contract-review'),(r'document-summary|document_summary','summaries'),(r'citation|legal.research|^research$','research'),(r'opponent','opponent-analysis'),(r'patent','patents'),(r'trademark','trademarks'),(r'intake.*build|structured.intake|leads/forms','intake-forms'),(r'intake|leads','leads'),(r'translat|multilingual|multilang|detect-language','translation'),(r'document.draft|ai-draft|ai-drafted','drafting'),(r'multi.state|multi.jurisdiction','compliance'),(r'case.*(analysis|assessment|outcome|predict)|matter-outcome|predictions','case-analysis'),(r'conflict','conflicts'),
(r'cle-tracker','cle'),(r'malpractice','malpractice'),(r'client.*survey|client-satisfaction','surveys'),(r'billing-rates','billing-rates'),(r'time-billing|billing/time|timesheet|time-entry|time_entry|time-capture|mobile-time|^time$','time'),(r'invoice|billing','billing'),(r'expense','expenses'),(r'court.date|calendar','calendar'),(r'deadline|case-tracking-beyond','deadlines'),(r'notification','notifications'),(r'email-draft|email_draft|communications|messages','messages'),(r'document|vault|uploads','documents'),(r'reports|analytics|reporting','reports'),(r'custom-viz|custom-views|insights/timeline','saved-views'),(r'operations|tasks','tasks'),(r'filing-service','filing-service'),(r'filings','filings'),(r'^clients','clients'),(r'^cases|^matters','matters'),(r'^contacts','contacts'),(r'^notes','notes'),(r'template','templates'),(r'firm-website','website'),(r'settings/users|^team','team')]
exact={'document_draft':'drafting','contract_review':'contract-review','legal_research':'research','deposition_summary':'depositions','conflict_check':'conflicts','document_summary':'summaries','case_outcome':'case-analysis','billing_optimizer':'billing','court_date_tracker':'calendar','immigration_form':'immigration-forms','client_intake':'leads','email_draft':'messages','time_entry':'time'}
ignored=[];unmapped=[]
def classify(module,key):
 key=key.strip('/');tail=key.rsplit('/',1)[-1]
 if key in extension['aliases'].get(module,{}):return extension['aliases'][module][key]
 if key=='settings/integrations':return 'connections'
 if key.startswith('portal/') and 'chat' not in key:return 'client-portal'
 if 'templates' in key:return 'templates'
 if key.startswith('form/'):return 'drafting'
 if key in special.get(module,{}):return special[module][key]
 if key in exact:return exact[key]
 for pattern,id in rules:
  if re.search(pattern,key,re.I):return id
 if key in byid:return key
 return None
excluded_exact={'','dashboard','home','login','register','forgot-password','reset-password','verify-email','about','api','blog','careers','contact','features','help-center','integrations','partners','practice-areas','press','pricing','privacy','privacy-policy','terms','terms-of-service','disclaimer','cookies','cookie-policy','refund-policy','sitemap.xml','robots.txt','services','faq','status','settings','preferences','test-config','test-auth','config','usage','test','history','suggestions','list','ai','ai-center','advanced-ai','batch03','extensions'}
routes=json.loads((ROOT/'reports/route-inventory.json').read_text())
for r in routes:
 key=r['path'].strip('/');source=dict(module=r['module'],path=r['path'],source=r['source'],kind='route')
 if key in extension['ignored'].get(r['module'],{}):
  ignored.append(dict(**source,reason=extension['ignored'][r['module']][key]));continue
 if key in excluded_exact or key.startswith(('features/','auth/')) or key in ['portal/login','portal/logout']:
  ignored.append(dict(**source,reason='Container, marketing, authentication or infrastructure; included within the shared workspace rather than as a duplicate feature.'));continue
 # Record-specific create/edit/detail routes belong to their parent feature, not extra sidebar items.
 id=classify(r['module'],key)
 if not id:
  if re.search(r'[:\[\]]',key): ignored.append(dict(**source,reason='Record-specific action or callback, not a standalone feature.'))
  else:unmapped.append(source)
 else:byid[id]['sources'].append(source)
panels=json.loads((ROOT/'reports/source-feature-panels.json').read_text())
for panel in panels:
 for item in panel['entries']:
  key=item.get('id') or item.get('slug') or item.get('path') or item.get('key')
  if key.strip('/') in extension['ignored'].get(panel['module'],{}):continue
  id=classify(panel['module'],key)
  source=dict(module=panel['module'],path=item.get('path') or item.get('endpoint') or '#'+key,source=panel['source'],kind='panel',label=item.get('title') or item.get('label') or key)
  if not id:unmapped.append(source);continue
  f=byid[id];f['sources'].append(source)
  if item.get('ai') or panel['name'] in ['aiFeatures','TOOLS','tools']:f['ai']=True
  # Preserve structured domain form fields from original app metadata.
  if panel['name']=='features' or (panel['name']=='pages' and f['id'] in {d['id'] for d in extension['features']}):
   existing={x['name']:x for x in f['fields']}
   for raw in item.get('fields',[]):
    field=dict(name=raw,label=raw.replace('_',' ').capitalize(),type='text') if isinstance(raw,str) else raw.copy()
    if field.get('name') in ['title','status','notes','id','user_id','client_id','case_id','matter_id'] or field.get('name') in ['access_info','password','is_encrypted','file_size']:continue
    field={k:v for k,v in field.items() if k in ['name','label','type','options','required']}
    if field.get('name'):existing[field['name']]={**existing.get(field['name'],{}),**field}
   f['fields']=list(existing.values())
# Capabilities mounted only as APIs still get first-class sidebar entries.
api_extra={'website':'apps/salesforce/src/app/api/firm-website-gen/route.ts','security':'apps/legal-documents/routes/gap_no_multi_tenant_law_firm_isolation.js','webhooks':'apps/legal-documents/routes/gap_no_webhooks_for_billing_e_signature.js','intake-forms':'apps/legal-documents/routes/ai-intake-builder.js'}
for id,source in api_extra.items():
 if (ROOT/source).exists():byid[id]['sources'].append(dict(module=source.split('/')[1],path='(API capability)',source=source,kind='api'))
for f in features:
 if f['id'] in ['contract-review','compliance','documents','drafting','summaries','negotiations']:
  f['fields'].append(dict(name='contract_id',label='Contract',type='reference',reference='contracts')) if not any(x['name']=='contract_id' for x in f['fields']) else None
 if f['id'] in ['negotiations','mediation','evidence']:
  f['fields'].append(dict(name='tenancy_id',label='Tenancy',type='reference',reference='tenancies'))
 f['sources']=list({(s['module'],s['path'],s['source'],s['kind']):s for s in f['sources']}.values())
 for field in f['fields']:
  if field['name'] in ['contract_id','tenancy_id']:
   field.update(type='reference',reference='contracts' if field['name']=='contract_id' else 'tenancies',label='Contract' if field['name']=='contract_id' else 'Tenancy')
 f['fields']=[x for x in f['fields'] if x['name'] not in ['title','status','notes']]
 f['owner']=f['sources'][0]['module'] if f['sources'] else 'workspace'
 f['path']='/features/'+f['id'];f['alternatives']=[]
 if f['mode']!='records':f['ai']=False
 f['description']=('Prepare '+f['title'].lower()+' requests and track their status. A provider connection is required to execute them.' if f['mode']=='integration' else f['description'])
(ROOT/'config/merged-features.json').write_text(json.dumps(features,indent=2)+'\n')
report=dict(features=len(features),mappedSources=sum(len(f['sources']) for f in features),ignoredRoutes=ignored,unmappedSources=unmapped,withoutSource=[f['id'] for f in features if not f['sources']],mergedGroups=[dict(id=f['id'],title=f['title'],sources=len(f['sources'])) for f in features if len(f['sources'])>1])
(ROOT/'reports/feature-merge-coverage.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({k:v for k,v in report.items() if k not in ['ignoredRoutes','mergedGroups']},indent=2))
